[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "alith"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
description = "Alith Python SDK"
license = { text = "Apache-2.0" }
dependencies = [
    "pydantic",
    "pydantic_config",
    "requests",
    "web3<8.0.0,>=7.6.0",
    "rsa",
    "python-gnupg",
    "aiohttp",
    "flask",
    "uvicorn",
    "fastapi",
    "dstack-sdk<0.3.0,>=0.2.1"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "black",
    "isort",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "alith._alith"
python-source = "."

[tool.ruff.lint]
ignore = ["F403", "F405"]
