[package]
description = "Managing Devices and Builds for LLMs"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "alith-devices"
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
colorful.workspace = true
indenter.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
nvml-wrapper = { version = "0.11.0" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-metal = { version = "0.3.1", features = ["MTLDevice"] }
