[package]
name = "alith-node-sdk"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
alith.workspace = true
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16.17", default-features = false, features = ["napi4", "tokio_rt", "async"] }
napi-derive = "2.16.13"
napi-sys = "2.4.0"
once_cell = "1.21.3"
futures = "0.3.31"

[build-dependencies]
napi-build = "2.2.1"
